version: '3'
services: 
    flask-app:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./flask-app
        ports:
            - '5000:5000'
    
    node-app:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./node-app
        ports:
            - '8000:8000'
        depends_on: 
            - flask-app    